#ifndef WIFICREDHTML_h
#define WIFICREDHTML_h
#include <Arduino.h>


const String SSIDTOKEN = "$SSIDTOKEN$";
const String PWDTOKEN = "$PWDTOKEN$";

String htmlWifiPage = "<!DOCTYPE html>\n"
"<html>\n"
"  <head>\n"
"    <title>Zugangsdaten WLAN </title>\n"
"    <meta charset=\"utf-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
"\n"
"    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.4.1/css/all.css\" integrity=\"sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz\" crossorigin=\"anonymous\">\n"
"    \n"
"    <script>  \n"
"      const togglePassword = document.querySelector('#togglePassword');\n"
"      const password = document.querySelector('#id_password');\n"
"\n"
"      togglePassword.addEventListener('click', function (e) {\n"
"        // toggle the type attribute\n"
"        const type = password.getAttribute('type') === 'password' ? 'text' : 'password';\n"
"        password.setAttribute('type', type);\n"
"        // toggle the eye slash icon\n"
"        this.classList.toggle('fa-eye-slash');\n"
"      });\n"
"    </script>  \n"
"\n"
"    <style>\n"
"      html, body {\n"
"      display: flex;\n"
"      justify-content: center;\n"
"      height: 100%;\n"
"      }\n"
"      body, div, h1, form, input, p { \n"
"      padding: 0;\n"
"      margin: 0;\n"
"      outline: none;\n"
"      font-family: Roboto, Arial, sans-serif;\n"
"      font-size: 16px;\n"
"      color: #666;\n"
"      }\n"
"      h1 {\n"
"      padding: 10px 0;\n"
"      font-size: 32px;\n"
"      font-weight: 300;\n"
"      text-align: center;\n"
"      }\n"
"      p {\n"
"      font-size: 12px;\n"
"      }\n"
"      hr {\n"
"      color: #a9a9a9;\n"
"      opacity: 0.3;\n"
"      }\n"
"      .main-block {\n"
"      max-width: 340px; \n"
"      min-height: 460px; \n"
"      padding: 10px 0;\n"
"      margin: auto;\n"
"      border-radius: 5px; \n"
"      border: solid 1px #ccc;\n"
"      box-shadow: 1px 2px 5px rgba(0,0,0,.31); \n"
"      background: #ebebeb; \n"
"      }\n"
"      form {\n"
"      margin: 0 10px;\n"
"      }\n"
"      .account-type, .gender {\n"
"      margin: 15px 0;\n"
"      }\n"
"      input[type=radio] {\n"
"      display: none;\n"
"      }\n"
"      label#icon {\n"
"      margin: 0;\n"
"      border-radius: 5px 0 0 5px;\n"
"      }\n"
"      label.radio {\n"
"      position: relative;\n"
"      display: inline-block;\n"
"      padding-top: 4px;\n"
"      margin-right: 20px;\n"
"      text-indent: 30px;\n"
"      overflow: visible;\n"
"      cursor: pointer;\n"
"      }\n"
"      label.radio:before {\n"
"      content: \"\";\n"
"      position: absolute;\n"
"      top: 2px;\n"
"      left: 0;\n"
"      width: 20px;\n"
"      height: 20px;\n"
"      border-radius: 50%;\n"
"      background: #1c87c9;\n"
"      }\n"
"      label.radio:after {\n"
"      content: \"\";\n"
"      position: absolute;\n"
"      width: 9px;\n"
"      height: 4px;\n"
"      top: 8px;\n"
"      left: 4px;\n"
"      border: 3px solid #fff;\n"
"      border-top: none;\n"
"      border-right: none;\n"
"      transform: rotate(-45deg);\n"
"      opacity: 0;\n"
"      }\n"
"      input[type=radio]:checked + label:after {\n"
"      opacity: 1;\n"
"      }\n"
"      input[type=text], input[type=password] {\n"
"      width: calc(100% - 80px);\n"
"      height: 36px;\n"
"      margin: 13px 0 0 -5px;\n"
"      padding-left: 10px; \n"
"      border-radius: 0 5px 5px 0;\n"
"      border: solid 1px #cbc9c9; \n"
"      box-shadow: 1px 2px 5px rgba(0,0,0,.09); \n"
"      background: #fff; \n"
"      }\n"
"      input[type=password] {\n"
"      margin-bottom: 15px;\n"
"      }\n"
"      #icon {\n"
"      display: inline-block;\n"
"      padding: 9.3px 15px;\n"
"      box-shadow: 1px 2px 5px rgba(0,0,0,.09); \n"
"      background: #1c87c9;\n"
"      color: #fff;\n"
"      text-align: center;\n"
"      }\n"
"      .btn-block {\n"
"      margin-top: 10px;\n"
"      text-align: center;\n"
"      }\n"
"      button {\n"
"      width: 100%;\n"
"      padding: 10px 0;\n"
"      margin: 10px auto;\n"
"      border-radius: 5px; \n"
"      border: none;\n"
"      background: #1c87c9; \n"
"      font-size: 14px;\n"
"      font-weight: 600;\n"
"      color: #fff;\n"
"      }\n"
"      button:hover {\n"
"      background: #26a9e0;\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"main-block\">\n"
"      <h1>Zugangsdaten<BR>WLAN</h1>\n"
"      <form action=\"save\" method='get'>\n"
"        <hr>\n"
//"        <label style=\"width:15px;\" id=\"icon\" for=\"ssid\" ><i></i></label>\n"
"        <label style=\"width:15px;\" id=\"icon\" for=\"ssid\" >"
"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15\" height=\"15\" preserveAspectRatio=\"xMidYMid meet\" viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"M12 6c3.537 0 6.837 1.353 9.293 3.809l1.414-1.414C19.874 5.561 16.071 4 12 4c-4.071.001-7.874 1.561-10.707 4.395l1.414 1.414C5.163 7.353 8.463 6 12 6zm5.671 8.307c-3.074-3.074-8.268-3.074-11.342 0l1.414 1.414c2.307-2.307 6.207-2.307 8.514 0l1.414-1.414z\"/><path fill=\"currentColor\" d=\"M20.437 11.293c-4.572-4.574-12.301-4.574-16.873 0l1.414 1.414c3.807-3.807 10.238-3.807 14.045 0l1.414-1.414z\"/><circle cx=\"12\" cy=\"18\" r=\"2\" fill=\"currentColor\"/></svg>"
        "</label>\n"
"        <input type=\"text\" name=\"ssid\" id=\"ssid\" placeholder=\"SSID\" value=\""+SSIDTOKEN+"\" required/>\n"

"        <label style=\"width:15px;\" id=\"icon\" for=\"wlankey\">"
"<svg xmlns=\"http://www.w3.org/2000/svg\"  width=\"35\" height=\"35\" preserveAspectRatio=\"xMidYMid meet\" viewBox=\"0 0 24 24\"><path fill=\"currentColor\" d=\"M7.5 6.5C7.5 8.981 9.519 11 12 11s4.5-2.019 4.5-4.5S14.481 2 12 2S7.5 4.019 7.5 6.5zM20 21h1v-1c0-3.859-3.141-7-7-7h-4c-3.86 0-7 3.141-7 7v1h17z\"/></svg>"


"        </label>\n"
"        <input type=\"text\" name=\"password\" autocomplete=\"current-password\" value=\""+PWDTOKEN+"\"required=\"\" id=\"id_password\">\n"


"<svg xmlns=\"http://www.w3.org/2000/svg\" style=\"margin-left: -30px; cursor: pointer;\" width=\"35\" height=\"35\" preserveAspectRatio=\"xMidYMid meet\" viewBox=\"0 0 36 36\"><path fill=\"currentColor\" d=\"M33.62 17.53c-3.37-6.23-9.28-10-15.82-10S5.34 11.3 2 17.53l-.28.47l.26.48c3.37 6.23 9.28 10 15.82 10s12.46-3.72 15.82-10l.26-.48Zm-15.82 8.9C12.17 26.43 7 23.29 4 18c3-5.29 8.17-8.43 13.8-8.43S28.54 12.72 31.59 18c-3.05 5.29-8.17 8.43-13.79 8.43Z\" class=\"clr-i-solid clr-i-solid-path-1\"/><circle cx=\"18.09\" cy=\"18.03\" r=\"6.86\" fill=\"currentColor\" class=\"clr-i-solid clr-i-solid-path-2\"/><path fill=\"none\" d=\"M0 0h36v36H0z\"/></svg>"
// "\n"
// "        <input type=\"password\" id=\"passowrdToggle\" value=\"\" placeholder=\"Password\">\n"
// "        <input class=\"far fa-eye\" type=\"button\" id=\"toggleButton\" value=\"👁\" />\n"
// "\n"
"        <hr>\n"
"        <div class=\"btn-block\">\n"
"          <button type=\"submit\" href=\"/\">Speichern</button>\n"
"        </div>\n"
"      </form>\n"
"    </div>\n"
"  </body>\n"
"</html>";

#endif


const String VALUETOKEN = "$VALUETOKEN$";

String htmlValuePage = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta http-equiv=\"refresh\" content=\"1\" >"
"    <meta charset=\"utf-8\">\n"
"    <title>title</title>\n"
"    <link rel=\"stylesheet\" href=\"style.css\">\n"
"    <script src=\"script.js\"></script>\n"
"  </head>\n"
"  <body>\n"
"    "+ VALUETOKEN +"\n"
"  </body>\n"
"</html>\n";