#ifndef table_h
#define table_h

#include <Arduino.h>
#include "textreplacement.h"

String tableHtmlPage = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<title>Solar Powermeter</title>\n"
" <meta http-equiv=\"refresh\" content=\"1\">"
"<script src=\"https://code.jquery.com/jquery-3.6.2.min.js\"></script>\n"
"<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n"
"\n"
"<style>\n"
"    html,\n"
"body,\n"
".intro {\n"
"  height: 100%;\n"
"}\n"
"\n"
"table td,\n"
"table th {\n"
"  text-overflow: ellipsis;\n"
"  white-space: nowrap;\n"
"  overflow: hidden;\n"
"}\n"
"\n"
"thead th {\n"
"  color: #fff;\n"
"}\n"
"\n"
".card {\n"
"  border-radius: .5rem;\n"
"}\n"
"\n"
".table-scroll {\n"
"  border-radius: .5rem;\n"
"}\n"
"\n"
".table-scroll table thead th {\n"
"  font-size: 1.25rem;\n"
"}\n"
"\n"
"table, th, td{\n"
"        border: 1px solid #666;\n"
"    }\n"
"</style>\n"
"\n"
"</head>\n"
"\n"
"<body>\n"
"              <div class=\"col-12\">\n"
"                <div class=\"card\">\n"
"              \n"
"                      <table class=\"table table-striped mb-0\">\n"
"                        <thead style=\"background-color: #002d72;\">\n"
"      \n"
"          <tr>\n"
"            <th scope=\"col\"></th>\n"
"            <th scope=\"col\">Spannung [V]</th>\n"
"            <th scope=\"col\">Strom [A]</th>\n"
"            <th scope=\"col\">Leistung [W]</th>\n"
"          </tr>\n"
"        </thead>\n"
"        <tbody>\n"
"          <tr>\n"
"            <td>Solar</td>\n"
"            <td id=\"solarvolt\">"+RPLC_SOLARVOLTAGE+"</td>\n"
"            <td id=\"solarcurrent\">"+RPLC_SOLARCURRENT+"</td>\n"
"            <td id=\"solarpower\">"+RPLC_SOLARPOWER+"</td>\n"
"          </tr>\n"
"          <tr>\n"
"            <td>Batterie</td>\n"
"            <td id=\"batterievolt\">"+RPLC_BATTVOLTAGE+"</td>\n"
"            <td id=\"batteriecurrent\">"+RPLC_BATTCURRENT+"</td>\n"
"            <td id=\"batteriepower\">"+RPLC_BATTPOWER+"</td>\n"
"          </tr>\n"
"          <tr>\n"
"            <td>Verbraucher</td>\n"
"            <td id=\"loadvolt\">"+RPLC_LOADVOLTAGE+"</td>\n"
"            <td id=\"loadcurrent\">"+RPLC_LOADCURRENT+"</td>\n"
"            <td id=\"loadpower\">"+RPLC_LOADPOWER+"</td>\n"
"          </tr>\n"
"        </tbody>\n"
"    </table>\n"
"  </div>\n"
"<BR>info: "+RPLC_INFO+" "
"</div>\n"
"\n"
"</body>\n"
"</html>";
#endif